// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

#define BASE_LAYER  (0)
#define UP_LAYER    (1)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
 [BASE_LAYER] = LAYOUT(
  KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINUS, KC_EQUAL,
  KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BACKSPACE,
  KC_CAPS_LOCK, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SEMICOLON, KC_QUOTE,
  KC_LEFT_SHIFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA, KC_DOT, KC_SLASH, KC_RIGHT_SHIFT,
  KC_LEFT_CTRL, KC_LEFT_ALT, KC_LEFT_GUI, KC_ESCAPE, KC_SPACE, TT(UP_LAYER), TT(BASE_LAYER), KC_SPACE, KC_ENTER, KC_KB_VOLUME_DOWN, KC_KB_MUTE, KC_KB_VOLUME_UP
 ),

 [UP_LAYER] = LAYOUT(
  KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_LEFT_BRACKET, KC_RIGHT_BRACKET, KC_MINUS, KC_EQUAL,
  KC_GRAVE, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BACKSPACE,
  KC_CAPS_LOCK, KC_B, KC_C, KC_D, KC_E, KC_F, KC_G, KC_H, KC_I, KC_J, KC_K, KC_L,
  KC_LEFT_SHIFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMMA, KC_DOT, KC_BACKSLASH, KC_RIGHT_SHIFT,
  KC_LEFT_CTRL, KC_LEFT_ALT, KC_LEFT_GUI, KC_ESCAPE, KC_SPACE, TT(UP_LAYER), TT(BASE_LAYER), KC_SPACE, KC_ENTER, KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK
 )
};
